[package]
name = "mulm"
version = "0.1.0"
authors = ["Aria Stewart <aredridel@dinhe.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mailparse = "^0.12.1"
